services:
  mongo:
    image: mongo:7.0
    container_name: farm_auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./
    container_name: farm_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data: {}
