.PHONY: app api i 

dev:
	cd backend && npm run dev & cd frontend && npm run dev

build:
	cd frontend && npm run build

app/dev:
	cd frontend && npm run dev

app/build:
	cd frontend && npm run build

api/dev:
	cd backend && npm run dev


i install:
	cd backend && npm install
	cd frontend && npm install

