version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: fam-todo-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fam_todo
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: fam-todo-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
