services:
  mongo:
    image: mongo:7.0
    container_name: mongo_farm_todo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo_data:
