import dotenv from "dotenv";
dotenv.config();

export const {
  MONGODB_URI,
  DB_NAME,
  PORT,
  FRONT_END_ORIGIN,
  JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN,
  JWT_REFRESH_SECRET,
  RESEND_API_KEY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_SECRET,
} = process.env;
